#!/usr/bin/with-contenv bash

PUID=${PUID:-1000}
PGID=${PGID:-100}

usermod -o -u "$PUID" guardian
groupmod -o -g "$PGID" users

if [[ ! -d /mnt/config/home/guardian ]]; then
  s6-setuidgid guardian mkdir -p /mnt/config/home/guardian
fi